import type { IKitStrings } from "./kitStrings";

/**
 * Dutch (nl-NL) chrome strings, Microsoft Dynamics terminology (Nieuw,
 * Geavanceerd, Zoeken, Bewerken, Vernieuwen, Terug, Volgende, Ga naar vandaag,
 * Tegenpartij, ...). Registered as "nl" by kitStrings. The EN dash in the
 * record-range strings matches the English table (never an em dash).
 */
export const dutchKitStrings: IKitStrings = {
  lookForRecords: "Records zoeken",
  lookFor: (fieldLabel) => `${fieldLabel} zoeken`,
  noRecordsFound: "Geen records gevonden",
  typeToSearch: "Typ om te zoeken",
  loading: "Laden…",
  working: "Bezig…",
  newLabel: "Nieuw",
  finish: "Voltooien",
  advanced: "Geavanceerd",
  changeTable: "Tabel wijzigen",
  browseRecords: "Door records bladeren",
  clearValue: "Waarde wissen",
  searchRecords: "Records zoeken",
  closeSearch: "Zoeken sluiten",
  lookupResults: "Zoekresultaten",
  loadingRows: "Rijen laden",
  recordRange: "Recordbereik",
  previousPage: "Vorige pagina",
  nextPage: "Volgende pagina",
  firstPage: "Eerste pagina",
  lastPage: "Laatste pagina",
  currentPage: "Huidige pagina",
  jumpToPage: "Ga naar pagina",
  moreDetailsForRecord: (name) => `Meer details voor record: ${name}`,
  pageN: (page) => `Pagina ${page}`,
  pageNOfM: (page, count) => `Pagina ${page} van ${count}`,
  showingRecords: (from, to) => `Records ${from}–${to} weergegeven`,
  showingRecordsOfTotal: (from, to, total) => `Records ${from}–${to} van ${total} weergegeven`,
  viewLoadError: "Deze weergave kan niet worden geladen in deze omgeving.",
  recordsLoadError: "De records van deze weergave kunnen niet worden geladen in deze omgeving.",
  fieldUnavailable: "Niet beschikbaar in deze omgeving.",
  pickerUnavailable: "De recordkiezer kan niet worden geopend in deze omgeving.",
  activityTypeRequired: "Activiteitstypecode is vereist in de weergave om de records te openen.",
  searchFailed: "De zoekopdracht kan niet worden voltooid. Probeer het opnieuw.",
  platformWaveTooOld:
    "Dit besturingselement vereist een nieuwere releasegolf van het platform dan deze omgeving biedt. Vraag uw beheerder om de releasegolf van de omgeving bij te werken.",
  back: "Terug",
  next: "Volgende",
  edit: "Bewerken",
  refresh: "Vernieuwen",
  deleteLabel: "Verwijderen",
  deleteWithCount: (count) => `Verwijderen (${count})`,
  search: "Zoeken",
  noDataAvailable: "Geen gegevens beschikbaar",
  dataGridLabel: "Gegevensraster",
  selectAllRows: "Alle rijen selecteren",
  resizeColumn: (columnName) => `Formaat van kolom ${columnName} wijzigen`,
  gridActions: "Rasteracties",
  activityActions: "Activiteitenacties",
  goToToday: "Ga naar vandaag",
  prevMonthAriaLabel: "Ga naar vorige maand",
  nextMonthAriaLabel: "Ga naar volgende maand",
  prevYearAriaLabel: "Ga naar vorig jaar",
  nextYearAriaLabel: "Ga naar volgend jaar",
  counterpartyHeader: "Tegenpartij",
  moreParties: (count) => `(+${count} meer)`,
  unnamedRecord: "(naamloos)",
  untitledActivity: "(zonder titel)",
  noActivities: "Geen activiteiten.",
  noMatchingActivities: "Geen overeenkomende activiteiten.",
  searchActivitiesPlaceholder: "Zoeken op onderwerp of tegenpartij",
  loadMore: "Meer laden",
  shownOfTotal: (shown, total) => `${shown} van ${total}`,
  shownCount: (shown) => `${shown} weergegeven`,
  noDescriptionAuthored: "Er is geen beschrijving opgesteld voor deze kolom.",
};
