import type { IKitStrings } from "./kitStrings";

/**
 * Spanish (es-ES) interface strings, usted register, Microsoft Dynamics
 * terminology. Anchor terms (Nuevo, Avanzada, Buscar, Editar, Actualizar,
 * Atrás, Siguiente, Ir a hoy, Contraparte, ...) were captured live from the
 * platform UI on a Spanish org. Registered as "es" by kitStrings. The EN dash
 * in the record-range strings matches the English table (never an em dash).
 */
export const spanishKitStrings: IKitStrings = {
  lookForRecords: "Buscar registros",
  lookFor: (fieldLabel) => `Buscar ${fieldLabel}`,
  noRecordsFound: "No se encontraron registros",
  typeToSearch: "Escriba para buscar",
  loading: "Cargando…",
  working: "Procesando…",
  newLabel: "Nuevo",
  finish: "Finalizar",
  advanced: "Avanzada",
  changeTable: "Cambiar tabla",
  browseRecords: "Examinar registros",
  clearValue: "Borrar valor",
  searchRecords: "Buscar registros",
  closeSearch: "Cerrar búsqueda",
  lookupResults: "Resultados de búsqueda",
  loadingRows: "Cargando filas",
  recordRange: "Intervalo de registros",
  previousPage: "Página anterior",
  nextPage: "Página siguiente",
  firstPage: "Primera página",
  lastPage: "Última página",
  currentPage: "Página actual",
  jumpToPage: "Ir a la página",
  moreDetailsForRecord: (name) => `Más detalles del registro: ${name}`,
  pageN: (page) => `Página ${page}`,
  pageNOfM: (page, count) => `Página ${page} de ${count}`,
  showingRecords: (from, to) => `Mostrando registros ${from}–${to}`,
  showingRecordsOfTotal: (from, to, total) => `Mostrando registros ${from}–${to} de ${total}`,
  viewLoadError: "No se pudo cargar esta vista en este entorno.",
  recordsLoadError: "No se pudieron cargar los registros de esta vista en este entorno.",
  fieldUnavailable: "No disponible en este entorno.",
  pickerUnavailable: "No se pudo abrir el selector de registros en este entorno.",
  activityTypeRequired:
    "El código de tipo de actividad es obligatorio en la vista para abrir los registros.",
  searchFailed: "No se pudo completar la búsqueda. Inténtelo de nuevo.",
  platformWaveTooOld:
    "Este control necesita una oleada de lanzamiento de la plataforma más reciente que la que ofrece este entorno. Solicite al administrador que actualice la oleada de lanzamiento del entorno.",
  back: "Atrás",
  next: "Siguiente",
  edit: "Editar",
  refresh: "Actualizar",
  deleteLabel: "Eliminar",
  deleteWithCount: (count) => `Eliminar (${count})`,
  search: "Buscar",
  noDataAvailable: "No hay datos disponibles",
  dataGridLabel: "Cuadrícula de datos",
  selectAllRows: "Seleccionar todas las filas",
  resizeColumn: (columnName) => `Cambiar el tamaño de la columna ${columnName}`,
  gridActions: "Acciones de la cuadrícula",
  activityActions: "Acciones de actividad",
  goToToday: "Ir a hoy",
  prevMonthAriaLabel: "Ir al mes anterior",
  nextMonthAriaLabel: "Ir al mes siguiente",
  prevYearAriaLabel: "Ir al año anterior",
  nextYearAriaLabel: "Ir al año siguiente",
  counterpartyHeader: "Contraparte",
  moreParties: (count) => `(+${count} más)`,
  unnamedRecord: "(sin nombre)",
  untitledActivity: "(sin título)",
  noActivities: "No hay actividades.",
  noMatchingActivities: "No hay actividades coincidentes.",
  searchActivitiesPlaceholder: "Buscar por asunto o contraparte",
  loadMore: "Cargar más",
  shownOfTotal: (shown, total) => `${shown} de ${total}`,
  shownCount: (shown) => `${shown} mostrados`,
  noDescriptionAuthored: "No se ha redactado ninguna descripción para esta columna.",
};
